-- MySQL Script generated by MySQL Workbench
-- Fri Sep 13 14:02:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema frogsknow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema frogsknow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `frogsknow` DEFAULT CHARACTER SET utf8 ;
USE `frogsknow` ;

-- -----------------------------------------------------
-- Table `frogsknow`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frogsknow`.`species` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `continent` VARCHAR(45) NOT NULL,
  `short_description` VARCHAR(200) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `picture` VARCHAR(200) NOT NULL,
  `population` INT(15) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `name_scientific` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frogsknow`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frogsknow`.`author` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `frogsknow`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `frogsknow`.`article` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(90) NOT NULL,
  `date` DATE NOT NULL,
  `subtitle` VARCHAR(100) NOT NULL,
  `introduction` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `author_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_article_author_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_article_author`
    FOREIGN KEY (`author_id`)
    REFERENCES `frogsknow`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `frogsknow`.`species`
-- -----------------------------------------------------
START TRANSACTION;
USE `frogsknow`;
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (1, 'American Bullfrog', 'North America', 'Large, aggressive frog with a loud call, often outcompeting native species.', 'The American Bullfrog is the largest frog species in North America, reaching up to 8 inches in length. It has a robust body, powerful legs, and a distinctive, deep bellowing call. They are highly adaptable and have been introduced to many parts of the world, where they often become invasive, preying on local wildlife and disrupting ecosystems. Bullfrogs thrive in a variety of aquatic environments, including ponds, lakes, and marshes. Their diet includes insects, small mammals, and even other frogs.', 'frog1', 50000000, 'Olive', 'Lithobates catesbeianus');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (2, ' Red-Eyed Tree Frog', 'Central and South America', 'Iconic frog with bright red eyes and vibrant green body, known for its striking appearance.', 'The Red-Eyed Tree Frog is famous for its vivid coloration and striking red eyes, which are believed to startle predators. This nocturnal species is arboreal, spending most of its life in the trees of tropical rainforests. Its body is bright green, with blue and yellow flanks and orange toes. Despite its vivid colors, it is not venomous and relies on camouflage and sudden displays to deter predators. The species plays a key role in its ecosystem by controlling insect populations and serving as prey for larger animals.', 'frog2', 10000000, 'a', 'Agalychnis callidryas');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (3, 'African Clawed Frog', 'Africa ', 'Aquatic frog with unique claws, used widely in scientific research', 'The African Clawed Frog is fully aquatic and known for its clawed toes on its hind legs, which it uses to shred its food. Native to sub-Saharan Africa, it has been introduced worldwide due to its use in medical research, particularly in early pregnancy tests. These frogs have a flattened body and a smooth, slimy skin. Their presence in non-native areas often leads to competition with and displacement of local species. They are also notable for their regenerative abilities, which have been studied extensively.', 'frog3', 20000000 , 'a', 'Xenopus laevis');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (4, 'Dyeing Poison Dart Frog', 'South America', 'Brightly colored, toxic frog; its skin toxins were historically used by indigenous people to poison darts.', 'The Dyeing Poison Dart Frog is one of the many brilliantly colored poison dart frogs. It can have a variety of color morphs, from blue and black to yellow and black patterns. Native to the rainforests of the Guiana Shield, it secretes potent toxins through its skin as a defense against predators. The name “dyeing” comes from the practice of indigenous tribes who allegedly used the frog\'s toxins to dye the feathers of parrots. Despite its toxicity, the frog’s diet in captivity can eliminate its poison, making it a popular species in the pet trade.', 'frog4', 1000000, 'a', 'Dendrobates tinctorius');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (5, 'European Common Frog', 'Europe', 'A common frog species found across Europe, known for its adaptability to various habitats.', 'The European Common Frog is widely distributed across Europe, from the British Isles to Russia. It inhabits a range of environments, including woodlands, gardens, and wetlands. This frog is highly adaptable and can survive in both urban and rural settings. It hibernates during winter, often in mud or underwater. The species has smooth skin with a variable color palette, usually brown or olive, and is speckled with dark spots. Its breeding season is marked by large gatherings at ponds, where males call to attract females.', 'frog5', 100000000, 'a', 'Rana temporaria');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (6, 'Golden Poison Dart Frog', 'America', ' One of the most poisonous animals on Earth, with a striking golden color.', 'The Golden Poison Dart Frog is infamous for its potent toxins, which are powerful enough to kill large animals, including humans. Found in the rainforests of western Colombia, this small but deadly frog is bright golden yellow, making it highly visible in its environment. The toxins are derived from the frog\'s diet of certain ants and other small invertebrates. Indigenous peoples have used the frog’s toxins to poison the tips of their blow darts. Despite its lethal reputation, the species is under threat due to habitat destruction and pollution.', 'frog6', 5000, 'a', 'Phyllobates terribilis');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (7, 'Australian Green Tree Frog', 'Australia', 'Popular pet frog known for its docile nature and bright green color.', 'The Australian Green Tree Frog is one of the most well-known frogs in Australia and is popular as a pet due to its calm demeanor and ease of care. It has smooth, bright green skin, sometimes with white or blueish spots. This species is adapted to a variety of environments, from rainforests to urban areas, where it can often be found around homes and gardens. The frog secretes peptides through its skin that have antibiotic properties, leading to interest in medical research. It is nocturnal and primarily insectivorous.', 'frog7', 2000000, 'a', 'Litoria caerulea');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (8, 'Goliath Frog', 'Africa', 'The world’s largest frog, weighing up to 7 pounds, found in West Africa.', 'The Goliath Frog is the largest frog species on the planet, reaching lengths of over 12 inches and weights up to 7 pounds. It is found in a small range in Cameroon and Equatorial Guinea, where it inhabits fast-flowing rivers and waterfalls. Despite its size, the Goliath Frog is shy and reclusive. It feeds on a variety of prey, including insects, small mammals, and other amphibians. The species is under threat due to habitat destruction and hunting for food and the pet trade. Conservation efforts are in place, but the population is declining.', 'frog8', 100000, 'a', 'Conraua goliath');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (9, 'Amazon Milk Frog', 'South America', 'Large tree frog with striking blue and white coloration, known for its sticky skin secretion.', 'The Amazon Milk Frog is a striking tree frog species found in the Amazon Basin. It has a distinctive appearance, with pale blue and white skin marked by black or brown bands. The \"milk\" in its name refers to the sticky, milky secretion it produces when threatened, which is believed to deter predators. This frog is nocturnal and arboreal, spending most of its life in the trees. It thrives in humid environments, where it preys on insects and other small invertebrates. Despite its exotic appearance, it is increasingly popular in the pet trade.', 'frog9', 500000, 'a', 'Trachycephalus resinifictrix');
INSERT INTO `frogsknow`.`species` (`id`, `name`, `continent`, `short_description`, `description`, `picture`, `population`, `color`, `name_scientific`) VALUES (10, 'Northern Leopard Frog', 'North America', 'Named for its leopard-like spots, this frog is found in a variety of habitats across North America.', 'The Northern Leopard Frog is a well-known species native to Canada and the United States. It is easily recognized by its green to brown skin, covered with distinctive dark spots that resemble a leopard’s pattern. This frog inhabits a wide range of environments, including wetlands, grasslands, and forests. It is an important part of the food web, serving as both predator and prey. However, populations have been declining in some areas due to habitat loss, pollution, and disease.', 'frog10', 5000000, 'a', 'Lithobates pipiens  ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `frogsknow`.`author`
-- -----------------------------------------------------
START TRANSACTION;
USE `frogsknow`;
INSERT INTO `frogsknow`.`author` (`id`, `name`, `lastname`) VALUES (1, 'Hopper', 'McJumpface');
INSERT INTO `frogsknow`.`author` (`id`, `name`, `lastname`) VALUES (2, 'Clara', 'Transparent');
INSERT INTO `frogsknow`.`author` (`id`, `name`, `lastname`) VALUES (3, 'Melody', 'Croak');

COMMIT;


-- -----------------------------------------------------
-- Data for table `frogsknow`.`article`
-- -----------------------------------------------------
START TRANSACTION;
USE `frogsknow`;
INSERT INTO `frogsknow`.`article` (`id`, `title`, `date`, `subtitle`, `introduction`, `content`, `author_id`) VALUES (1, 'The Amazing Leap of the Common Frog', '2024-09-11', 'How Frogs’ Hopping Abilities Push the Boundaries of Biological Engineering', 'Frogs are renowned for their impressive jumping abilities, but what makes their leaps so extraordinary? These amphibians showcase some of the most efficient and powerful jumps in the animal kingdom. Let’s dive into the fascinating mechanics behind their incredible hops.', 'The common frog (Rana temporaria) can leap distances up to 20 times its body length, thanks to its specialized musculoskeletal system. The frogs\' powerful hind legs are equipped with elongated muscles and tendons that store and release energy like a spring. This mechanism allows them to execute explosive jumps, propelling them over obstacles and into new territories. Interestingly, the biomechanics of a frog’s leap have inspired engineers to design better shock absorbers and prosthetics. By mimicking the frogs\' spring-like energy storage, researchers are creating devices that enhance performance and comfort in human applications.\\n Another intriguing aspect of frog locomotion is their use of water surfaces to aid their jumps. Frogs often use water to cushion their landing or to gain extra propulsion. Observations have shown that frogs can adjust their jumping techniques based on the surface they are jumping from, optimizing their performance and conserving energy. This adaptability further highlights the complexity and efficiency of their movement strategies, showcasing an evolutionary advantage in diverse environments.', 1);
INSERT INTO `frogsknow`.`article` (`id`, `title`, `date`, `subtitle`, `introduction`, `content`, `author_id`) VALUES (2, 'The Mysterious Life of the Glass Frog', '2024-09-01', 'Exploring the World of Nature’s See-Through Amphibian', 'The glass frog is a marvel of nature with its translucent skin, allowing a view of its internal organs. This unique adaptation raises many questions about its evolutionary advantages and survival strategies.', 'Glass frogs (family Centrolenidae) possess a clear underside, which serves as a form of camouflage. Their transparency helps them blend in with the leaves and branches they inhabit, making it harder for predators to spot them. Additionally, their transparent skin may help regulate body temperature and reduce predation by visually confusing predators. Researchers are studying these frogs to understand how their skin transparency works and how it might inspire innovations in materials science, such as creating new types of camouflage or medical imaging technologies.', 2);
INSERT INTO `frogsknow`.`article` (`id`, `title`, `date`, `subtitle`, `introduction`, `content`, `author_id`) VALUES (3, 'The Remarkable Regeneration Powers of the African Clawed Frog', '2023-07-23', 'How the African Clawed Frog Defies Limits with its Healing Abilities', 'The African clawed frog (Xenopus laevis) is not just an ordinary amphibian. It has some astonishing regenerative abilities that are catching the attention of scientists worldwide. Let’s uncover the secrets behind its remarkable healing powers.', 'Unlike many other animals, the African clawed frog can regenerate lost limbs and even parts of its heart and brain. This ability is due to the presence of specific cells that can transform into various tissue types needed for repair. Researchers are investigating these cells to better understand regeneration processes, which could eventually lead to breakthroughs in human medicine for healing injuries or diseases. By studying the genetic and cellular mechanisms behind this frog’s regeneration, scientists hope to unlock new avenues for treating conditions like spinal cord injuries and degenerative diseases in humans.', 3);
INSERT INTO `frogsknow`.`article` (`id`, `title`, `date`, `subtitle`, `introduction`, `content`, `author_id`) VALUES (4, 'Frog Vocalizations: The Hidden Symphony of Amphibians', '2024-01-20', 'Decoding the Complex Sounds of Frog Communication', 'Frogs are not just quiet pond dwellers; they have an elaborate system of vocalizations used for communication. Each species has its unique calls that serve various purposes. Let’s explore the acoustic world of frogs and what their sounds mean.', 'Frog calls are used primarily for mating rituals, territory defense, and signaling danger. Different species produce distinct sounds that can range from a simple croak to a complex series of chirps and trills. For example, the American toad’s call is a deep, resonant trill, while the European tree frog emits a more melodic and rhythmic sound. Researchers use specialized equipment to study these vocalizations, which helps them understand frog behavior and ecology better. Additionally, analyzing these calls can provide insights into the health of amphibian populations and the impact of environmental changes', 3);

COMMIT;

